### ISSUE TITLE
Cannot install cluster_toolkit currently in a NERSC Anaconda environment

### ISSUE THREAD

**Issue by heather999** [tmcclintock/cluster_toolkit#11]
Hi, the group working on clmassmod requested we add this package to the NERSC python conda environment, but my initial attempts failed.  All I did was create a conda environment that cloned my root env, then cloned master from github, and tried to run python setup.py install

````
(clmassmod) desc@cori17:/global/common/software/lsst/common/miniconda/temp/cluster_toolkit> python setup.py install                                                                         
ln: failed to create symbolic link 'cluster_toolkit/include/include': File exists             
/tmp/easy_install-jji4hs6v/pytest-runner-4.2/.eggs/setuptools_scm-3.0.2-py3.6.egg/setuptools_scm/version.py:181: UserWarning: meta invoked without explicit configuration, will use defaults where required.                                                                              
zip_safe flag not set; analyzing archive contents...                                          

Installed /global/common/software/lsst/common/miniconda/temp/cluster_toolkit/.eggs/pytest_runner-4.2-py3.6.egg                                                                              
running install                                                                               
running bdist_egg                                                                             
running egg_info                                                                              
creating cluster_toolkit.egg-info                                                             
writing cluster_toolkit.egg-info/PKG-INFO                                                     
writing dependency_links to cluster_toolkit.egg-info/dependency_links.txt                     
writing requirements to cluster_toolkit.egg-info/requires.txt                                 
writing top-level names to cluster_toolkit.egg-info/top_level.txt                             
writing manifest file 'cluster_toolkit.egg-info/SOURCES.txt'                                  
reading manifest file 'cluster_toolkit.egg-info/SOURCES.txt'                                  
writing manifest file 'cluster_toolkit.egg-info/SOURCES.txt'                                  
installing library code to build/bdist.linux-x86_64/egg                                       
running install_lib                                                                           
running build_py                                                                              
creating build                                                                                
creating build/lib.linux-x86_64-3.6                                                           
creating build/lib.linux-x86_64-3.6/cluster_toolkit                                           
copying cluster_toolkit/peak_height.py -> build/lib.linux-x86_64-3.6/cluster_toolkit          
copying cluster_toolkit/averaging.py -> build/lib.linux-x86_64-3.6/cluster_toolkit            
copying cluster_toolkit/massfunction.py -> build/lib.linux-x86_64-3.6/cluster_toolkit         
copying cluster_toolkit/density.py -> build/lib.linux-x86_64-3.6/cluster_toolkit              
copying cluster_toolkit/__init__.py -> build/lib.linux-x86_64-3.6/cluster_toolkit             
copying cluster_toolkit/boostfactors.py -> build/lib.linux-x86_64-3.6/cluster_toolkit         
copying cluster_toolkit/xi.py -> build/lib.linux-x86_64-3.6/cluster_toolkit                   
copying cluster_toolkit/concentration.py -> build/lib.linux-x86_64-3.6/cluster_toolkit        
copying cluster_toolkit/bias.py -> build/lib.linux-x86_64-3.6/cluster_toolkit                 
copying cluster_toolkit/miscentering.py -> build/lib.linux-x86_64-3.6/cluster_toolkit         
copying cluster_toolkit/deltasigma.py -> build/lib.linux-x86_64-3.6/cluster_toolkit           
creating build/lib.linux-x86_64-3.6/cluster_toolkit/include                                   
copying cluster_toolkit/include/C_peak_height.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                       
copying cluster_toolkit/include/C_bias.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include
copying cluster_toolkit/include/C_averaging.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                         
copying cluster_toolkit/include/C_miscentering.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                      
copying cluster_toolkit/include/C_boostfactors.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                      
copying cluster_toolkit/include/C_deltasigma.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                        
copying cluster_toolkit/include/C_density.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                           
copying cluster_toolkit/include/C_power.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                             
copying cluster_toolkit/include/C_concentration.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                     
copying cluster_toolkit/include/C_xi.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include  
copying cluster_toolkit/include/C_massfunction.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                      
copying cluster_toolkit/include/constants.h -> build/lib.linux-x86_64-3.6/cluster_toolkit/include                                                                                           
running build_ext                                                                             
building 'cluster_toolkit._cluster_toolkit' extension                                         
creating build/temp.linux-x86_64-3.6                                                          
creating build/temp.linux-x86_64-3.6/src                                                      
Traceback (most recent call last):                                                            
  File "setup.py", line 35, in <module>                                                       
    tests_require=['pytest']                                                                  
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/core.py", line 148, in setup                                                    
    dist.run_commands()                                                                       
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/dist.py", line 955, in run_commands                                             
    self.run_command(cmd)                                                                     
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/dist.py", line 974, in run_command                                              
    cmd_obj.run()                                                                             
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run                             
    self.do_egg_install()                                                                     
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install                 
    self.run_command('bdist_egg')                                                             
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/cmd.py", line 313, in run_command                                               
    self.distribution.run_command(command)                                                    
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/dist.py", line 974, in run_command                                              
    cmd_obj.run()                                                                             
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 169, in run                          
    cmd = self.call_command('install_lib', warn_dir=0)                                        
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 155, in call_command                 
    self.run_command(cmdname)                                                                 
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/cmd.py", line 313, in run_command                                               
    self.distribution.run_command(command)                                                    
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/dist.py", line 974, in run_command                                              
    cmd_obj.run()                                                                             
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run                         
    self.build()                                                                              
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/command/install_lib.py", line 107, in build                                     
    self.run_command('build_ext')                                                             
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/cmd.py", line 313, in run_command                                               
    self.distribution.run_command(command)                                                    
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/dist.py", line 974, in run_command                                              
    cmd_obj.run()                                                                             
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run                           
    _build_ext.run(self)                                                                      
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run                        
    _build_ext.build_ext.run(self)                                                            
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/command/build_ext.py", line 339, in run                                         
    self.build_extensions()                                                                   
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/clmassmod/lib/python3.6/distutils/spawn.py", line 89, in _spawn_posix
    log.info(' '.join(cmd))
TypeError: sequence item 15: expected str instance, bytes found
```

**Comment by msyriac** [comment]
I get the same error when installing with Python 3 (but not with 2).

This is happening because at some point, a compile flag (the last one below) '-I/usr/include' is passed as type "bytes" instead of string:
```
['gcc', '-pthread', '-Wno-unused-result', '-Wsign-compare', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-march=x86-64', '-mtune=generic', '-O3', '-pipe', '-fstack-protector-strong', '-fno-plt', '-flto=4', '-fuse-linker-plugin', '-ffat-lto-objects', '-flto-partition=none', '-g', '-march=x86-64', '-mtune=generic', '-O3', '-pipe', '-fstack-protector-strong', '-fno-plt', '-march=x86-64', '-mtune=generic', '-O3', '-pipe', '-fstack-protector-strong', '-fno-plt', '-fPIC', '-Iinclude', '-I/usr/include/python3.7m', '-c', 'src/C_exclusion.c', '-o', 'build/temp.linux-x86_64-3.7/src/C_exclusion.o', b'-I/usr/include']
```
but I've had no luck in tracking down why that happens.

**Comment by tmcclintock** [comment]
Hey all, prompted by @msyriac attempting to install the toolkit with Python 3, I merged @rafaelgm9 's PR that updated everything. The problem (I believe) is that in `setup.py` I was using `subprocess.check_output` to evaluate GSL flags. The problem was that this function outputs a byte string. @rafaelgm9 fixed this by adding the `universal_newlines` argument.

Everything installs now in Python 3.7, and right now there is only some string related warning when I run the unit tests. So, I think it's fine to use this now. Thanks again to all of you for helping me get the package up to date!
