### ISSUE TITLE
Python 3 library file mismatch

### ISSUE THREAD

**Issue by msyriac** [tmcclintock/cluster_toolkit#13]
Another error specific to Python 3 when I try to import cluster_toolkit:

```
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    import setup_files
  File "/home/msyriac/repos/redmapper-lensing/tomfit/setup_files.py", line 12, in <module>
    import cluster_toolkit as ct
  File "/home/msyriac/.local/lib/python3.7/site-packages/cluster_toolkit-0.0.0-py3.7-linux-x86_64.egg/cluster_toolkit/__init__.py", line 19, in <module>
    _lib = _ffi.dlopen(lib_file)
  File "/home/msyriac/.local/lib/python3.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/msyriac/.local/lib/python3.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/msyriac/.local/lib/python3.7/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/home/msyriac/.local/lib/python3.7/site-packages/cluster_toolkit-0.0.0-py3.7-linux-x86_64.egg/cluster_toolkit/_cluster_toolkit.so': /home/msyriac/.local/lib/python3.7/site-packages/cluster_toolkit-0.0.0-py3.7-linux-x86_64.egg/cluster_toolkit/_cluster_toolkit.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/msyriac/.local/lib/python3.7/site-packages/cluster_toolkit-0.0.0-py3.7-linux-x86_64.egg/cluster_toolkit/_cluster_toolkit.so'
```

This happens because `_cluster_toolkit.so` actually has the filename `_cluster_toolkit.cpython-37m-x86_64-linux-gnu.so`. Working around by renaming for now.

**Comment by tmcclintock** [comment]
Ugh. Yes, I've seen this issue in other places. It is because Python 3 compiles C code in annoying ways now. I'll figure this out, but yes for now the best thing to do is to manually change the name.

**Comment by tmcclintock** [comment]
Fixed.
